/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuleDocumentsRouteRouteImport } from './routes/rule-documents/route'
import { Route as GeneralDocumentsRouteRouteImport } from './routes/general-documents/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuleDocumentsIndexRouteImport } from './routes/rule-documents/index'
import { Route as GeneralDocumentsIndexRouteImport } from './routes/general-documents/index'
import { Route as RuleDocumentsIdRouteImport } from './routes/rule-documents/$id'
import { Route as GeneralDocumentsIdRouteImport } from './routes/general-documents/$id'

const RuleDocumentsRouteRoute = RuleDocumentsRouteRouteImport.update({
  id: '/rule-documents',
  path: '/rule-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralDocumentsRouteRoute = GeneralDocumentsRouteRouteImport.update({
  id: '/general-documents',
  path: '/general-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleDocumentsIndexRoute = RuleDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuleDocumentsRouteRoute,
} as any)
const GeneralDocumentsIndexRoute = GeneralDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeneralDocumentsRouteRoute,
} as any)
const RuleDocumentsIdRoute = RuleDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RuleDocumentsRouteRoute,
} as any)
const GeneralDocumentsIdRoute = GeneralDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GeneralDocumentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/general-documents': typeof GeneralDocumentsRouteRouteWithChildren
  '/rule-documents': typeof RuleDocumentsRouteRouteWithChildren
  '/general-documents/$id': typeof GeneralDocumentsIdRoute
  '/rule-documents/$id': typeof RuleDocumentsIdRoute
  '/general-documents/': typeof GeneralDocumentsIndexRoute
  '/rule-documents/': typeof RuleDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/general-documents/$id': typeof GeneralDocumentsIdRoute
  '/rule-documents/$id': typeof RuleDocumentsIdRoute
  '/general-documents': typeof GeneralDocumentsIndexRoute
  '/rule-documents': typeof RuleDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/general-documents': typeof GeneralDocumentsRouteRouteWithChildren
  '/rule-documents': typeof RuleDocumentsRouteRouteWithChildren
  '/general-documents/$id': typeof GeneralDocumentsIdRoute
  '/rule-documents/$id': typeof RuleDocumentsIdRoute
  '/general-documents/': typeof GeneralDocumentsIndexRoute
  '/rule-documents/': typeof RuleDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/general-documents'
    | '/rule-documents'
    | '/general-documents/$id'
    | '/rule-documents/$id'
    | '/general-documents/'
    | '/rule-documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/general-documents/$id'
    | '/rule-documents/$id'
    | '/general-documents'
    | '/rule-documents'
  id:
    | '__root__'
    | '/'
    | '/general-documents'
    | '/rule-documents'
    | '/general-documents/$id'
    | '/rule-documents/$id'
    | '/general-documents/'
    | '/rule-documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneralDocumentsRouteRoute: typeof GeneralDocumentsRouteRouteWithChildren
  RuleDocumentsRouteRoute: typeof RuleDocumentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rule-documents': {
      id: '/rule-documents'
      path: '/rule-documents'
      fullPath: '/rule-documents'
      preLoaderRoute: typeof RuleDocumentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-documents': {
      id: '/general-documents'
      path: '/general-documents'
      fullPath: '/general-documents'
      preLoaderRoute: typeof GeneralDocumentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-documents/': {
      id: '/rule-documents/'
      path: '/'
      fullPath: '/rule-documents/'
      preLoaderRoute: typeof RuleDocumentsIndexRouteImport
      parentRoute: typeof RuleDocumentsRouteRoute
    }
    '/general-documents/': {
      id: '/general-documents/'
      path: '/'
      fullPath: '/general-documents/'
      preLoaderRoute: typeof GeneralDocumentsIndexRouteImport
      parentRoute: typeof GeneralDocumentsRouteRoute
    }
    '/rule-documents/$id': {
      id: '/rule-documents/$id'
      path: '/$id'
      fullPath: '/rule-documents/$id'
      preLoaderRoute: typeof RuleDocumentsIdRouteImport
      parentRoute: typeof RuleDocumentsRouteRoute
    }
    '/general-documents/$id': {
      id: '/general-documents/$id'
      path: '/$id'
      fullPath: '/general-documents/$id'
      preLoaderRoute: typeof GeneralDocumentsIdRouteImport
      parentRoute: typeof GeneralDocumentsRouteRoute
    }
  }
}

interface GeneralDocumentsRouteRouteChildren {
  GeneralDocumentsIdRoute: typeof GeneralDocumentsIdRoute
  GeneralDocumentsIndexRoute: typeof GeneralDocumentsIndexRoute
}

const GeneralDocumentsRouteRouteChildren: GeneralDocumentsRouteRouteChildren = {
  GeneralDocumentsIdRoute: GeneralDocumentsIdRoute,
  GeneralDocumentsIndexRoute: GeneralDocumentsIndexRoute,
}

const GeneralDocumentsRouteRouteWithChildren =
  GeneralDocumentsRouteRoute._addFileChildren(
    GeneralDocumentsRouteRouteChildren,
  )

interface RuleDocumentsRouteRouteChildren {
  RuleDocumentsIdRoute: typeof RuleDocumentsIdRoute
  RuleDocumentsIndexRoute: typeof RuleDocumentsIndexRoute
}

const RuleDocumentsRouteRouteChildren: RuleDocumentsRouteRouteChildren = {
  RuleDocumentsIdRoute: RuleDocumentsIdRoute,
  RuleDocumentsIndexRoute: RuleDocumentsIndexRoute,
}

const RuleDocumentsRouteRouteWithChildren =
  RuleDocumentsRouteRoute._addFileChildren(RuleDocumentsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneralDocumentsRouteRoute: GeneralDocumentsRouteRouteWithChildren,
  RuleDocumentsRouteRoute: RuleDocumentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
